SmokeTestAsp/Controllers/EvaluationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SmokeTestDBClassLibrary;

namespace SmokeTestAsp.Controllers
{
    public class EvaluationController : Controller
    {
        private SmokeTestsEntities db = new SmokeTestsEntities();

        // GET: Evaluation
        public ActionResult Index()
        {
            var report_Evaluations = db.Report_Evaluations.Include(r => r.Evaluator).Include(r => r.Release).Include(r => r.Report).Include(r => r.Status);
            return View(report_Evaluations.ToList());
        }

        // GET: Evaluation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report_Evaluation report_Evaluation = db.Report_Evaluations.Find(id);
            if (report_Evaluation == null)
            {
                return HttpNotFound();
            }
            return View(report_Evaluation);
        }

        // GET: Evaluation/Create
        public ActionResult Create()
        {
            ViewBag.Evaluator_ID = new SelectList(db.Evaluators, "Id", "Name");
            ViewBag.Release_ID = new SelectList(db.Releases, "Id", "Name");
            ViewBag.Report_ID = new SelectList(db.Reports, "Id", "Report_Name");
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Name");
            return View();
        }

        // POST: Evaluation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Release_ID,Evaluator_ID,Report_ID,Status_ID,Comment,DateAdded,AddedBy,DateModified,ModifiedBy")] Report_Evaluation report_Evaluation)
        {
            if (ModelState.IsValid)
            {
                db.Report_Evaluations.Add(report_Evaluation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Evaluator_ID = new SelectList(db.Evaluators, "Id", "Name", report_Evaluation.Evaluator_ID);
            ViewBag.Release_ID = new SelectList(db.Releases, "Id", "Name", report_Evaluation.Release_ID);
            ViewBag.Report_ID = new SelectList(db.Reports, "Id", "Report_Name", report_Evaluation.Report_ID);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Name", report_Evaluation.Status_ID);
            return View(report_Evaluation);
        }

        // GET: Evaluation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report_Evaluation report_Evaluation = db.Report_Evaluations.Find(id);
            if (report_Evaluation == null)
            {
                return HttpNotFound();
            }
            ViewBag.Evaluator_ID = new SelectList(db.Evaluators, "Id", "Name", report_Evaluation.Evaluator_ID);
            ViewBag.Release_ID = new SelectList(db.Releases, "Id", "Name", report_Evaluation.Release_ID);
            ViewBag.Report_ID = new SelectList(db.Reports, "Id", "Report_Name", report_Evaluation.Report_ID);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Name", report_Evaluation.Status_ID);
            return View(report_Evaluation);
        }

        // POST: Evaluation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Release_ID,Evaluator_ID,Report_ID,Status_ID,Comment,DateAdded,AddedBy,DateModified,ModifiedBy")] Report_Evaluation report_Evaluation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(report_Evaluation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Evaluator_ID = new SelectList(db.Evaluators, "Id", "Name", report_Evaluation.Evaluator_ID);
            ViewBag.Release_ID = new SelectList(db.Releases, "Id", "Name", report_Evaluation.Release_ID);
            ViewBag.Report_ID = new SelectList(db.Reports, "Id", "Report_Name", report_Evaluation.Report_ID);
            ViewBag.Status_ID = new SelectList(db.Status, "Id", "Name", report_Evaluation.Status_ID);
            return View(report_Evaluation);
        }

        // GET: Evaluation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report_Evaluation report_Evaluation = db.Report_Evaluations.Find(id);
            if (report_Evaluation == null)
            {
                return HttpNotFound();
            }
            return View(report_Evaluation);
        }

        // POST: Evaluation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Report_Evaluation report_Evaluation = db.Report_Evaluations.Find(id);
            db.Report_Evaluations.Remove(report_Evaluation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SmokeTestAsp/Controllers/SSRSMenuController.cs
using SmokeTestDBClassLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmokeTestAsp.Controllers
{
    public class SSRSMenuController : Controller
    {
        private SmokeTestsEntities db = new SmokeTestsEntities();
        private readonly string path = "http://wcsqldev02/ReportServer/Pages/ReportViewer.aspx?%2fKalamata%2fKalamataDEV%2fReports%2f{0}&rs%3aCommand=Render";
        //private string path1 = "http://wcsqldev02/Reports/report/Kalamata/KalamataDEV/Reports/{0}";
        // GET: SSRSMenu
        public ActionResult Index()
        {
            ViewBag.Report = string.Format(path, "CaseloadDashboard");
            return View();
        }

        public ActionResult Menu()
        {
            var menuList = db.MainMenus;
            ViewBag.Report = string.Format(path, "CaseloadDashboard");
            return View(menuList);
        }

        public ActionResult GotoReport(string report)
        {
            var menuList = db.MainMenus;
            ViewBag.Report = string.Format(path, report);
            ViewBag.ReportMenu = report;
            return View("Menu",menuList);
        }

        public ActionResult FillMenu(int mainMenuId)
        {
            var menuSection = db.MainMenus.Find(mainMenuId);
            ViewBag.MenuHeader = menuSection.DisplayLabel;
            var itms = menuSection.MainMenuSubMenus;
            return PartialView("~/Views/Shared/_MenuItem.cshtml", itms);
        }
    }
}

SmokeTestAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav n">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Reports", "Index", "Reports")</li>
                    <li>@Html.ActionLink("Sections", "Index", "Sections")</li>
                    <li>@Html.ActionLink("Evaluations", "Index", "Evaluation")</li>
                    <li>@Html.ActionLink("The Reports", "Menu", "SSRSMenu")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SmokeTestAsp/Views/Shared/_MenuItem.cshtml
@model IEnumerable<SmokeTestDBClassLibrary.MainMenuSubMenu>

<li>
    <a class="menuButton" data-toggle="collapse" data-target= @string.Format("#{0}SubMenu", ViewBag.MenuHeader) href="#"> @ViewBag.MenuHeader <span class="caret"></span> </a>
    <div id= @string.Format("{0}SubMenu", ViewBag.MenuHeader) class="collapse show menu">
        <ul>
            @foreach (var item in Model)
            {
                if (ViewBag.ReportMenu == item.ReportName)
                {
                    <li class="nav-item btn btn-block menuButton">@Html.ActionLink(item.SubMenuDisplayLabel, "GotoReport", "SSRSMenu", new { report = item.ReportName }, null)</li>
                }
                else
                {
                    <li class="nav-item btn btn-block menuButton">@Html.ActionLink(item.SubMenuDisplayLabel, "GotoReport", "SSRSMenu", new { report = item.ReportName }, null)</li>
                }
            }
        </ul>
    </div>
</li>
@*<div class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> @ViewBag.MenuHeader <span class="caret"></span> </a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">

    </ul>
</div>*@